Feature: test

  Scenario Outline: User Management Create users - basic fields <login> <passwd>
    When I create a user:
      | login             | <login>             |
      | passwd            | <passwd>            |
      | passwdConfirm     | <passwdConfirm>     |
      | expDate           | <expDate>           |
      | startupNamespace  | <startupNamespace>  |
      | startupTagRoutine | <startupTagRoutine> |
    Then the Edit User page validation elements are confirmed
      | responseText  | <responseText>  |
      | nameHint      | <nameHint>      |
      | passwdHint    | <passwdHint>    |
      | routineHint   | <routineHint>   |
      | namespaceHint | <namespaceHint> |
    And I confirm the user has been created successfully

    Examples:
      | login                        | passwd                            | passwdConfirm                     | expDate    | startupNamespace | startupTagRoutine | status | responseText                                                                                                                                                                                                       | nameHint  | passwdHint | namespaceHint                         | routineHint                                            |
      | newUser1                     | newUser1                          | newUser1                          |            |                  |                   | true   | User saved.                                                                                                                                                                                                        |           |            |                                       |                                                        |
      |                              | missingNameUser                   | missingNameUser                   |            |                  |                   | false  | There was a problem with the form. See the highlighted fields below.                                                                                                                                               | Required. |            |                                       |                                                        |
      | missingPasswdUser            |                                   | missingPasswdUser                 |            |                  |                   | false  | There was a problem with the form. See the highlighted fields below.                                                                                                                                               |           | Required.  |                                       |                                                        |
      | nonMatchingConfirmPasswdUser | passwd                            | nonMatchingPasswd                 |            |                  |                   | false  | There was a problem with the form. See the highlighted fields below.                                                                                                                                               |           | Required.  |                                       |                                                        |
      | validDateLeapYear            | passwd                            | passwd                            | 2020-02-29 |                  |                   | true   | User saved.                                                                                                                                                                                                        |           |            |                                       |                                                        |
      | invalidCharDate              | passwd                            | passwd                            | abc        |                  |                   | false  | ERROR #944: Invalid expiration date ERROR #7204: Datatype value '-1' less than MINVAL allowed of 0 > ERROR #5802: Datatype validation failed on property 'Security.Users:ExpirationDate', with value equal to "-1" |           |            |                                       |                                                        |
      | invalidValueDate1            | passwd                            | passwd                            | 2017-02-29 |                  |                   | false  | ERROR #944: Invalid expiration date ERROR #7204: Datatype value '-1' less than MINVAL allowed of 0 > ERROR #5802: Datatype validation failed on property 'Security.Users:ExpirationDate', with value equal to "-1" |           |            |                                       |                                                        |
      | invalidValueDate2            | passwd                            | passwd                            | 2017-13-29 |                  |                   | false  | ERROR #944: Invalid expiration date ERROR #7204: Datatype value '-1' less than MINVAL allowed of 0 > ERROR #5802: Datatype validation failed on property 'Security.Users:ExpirationDate', with value equal to "-1" |           |            |                                       |                                                        |
      | invalidFormatDate            | passwd                            | passwd                            | 1/1/2025   |                  |                   | false  | ERROR #944: Invalid expiration date ERROR #7204: Datatype value '-1' less than MINVAL allowed of 0 > ERROR #5802: Datatype validation failed on property 'Security.Users:ExpirationDate', with value equal to "-1" |           |            |                                       |                                                        |
      | passwdOverMaxConfigLength    | 123456789012345678901234567890123 | 123456789012345678901234567890123 |            |                  |                   | false  | ERROR #845: Password does not match length or pattern requirements                                                                                                                                                 |           | Required.  |                                       |                                                        |
      | passwdUnderMaxConfigLength   | 12                                | 12                                |            |                  |                   | false  | ERROR #845: Password does not match length or pattern requirements                                                                                                                                                 |           | Required.  |                                       |                                                        |
      | routineNotInNamespace        | passwd                            | passwd                            |            | %SYS             | ^NoRoutine        | false  | There was a problem with the form. See the highlighted fields below.                                                                                                                                               |           | Required.  |                                       | Routine 'NoRoutine' does not exist in namespace '%SYS' |
      | routineWithNoNamespace       | passwd                            | passwd                            |            |                  | ^NoNamespace      | false  | There was a problem with the form. See the highlighted fields below.                                                                                                                                               |           | Required.  | Required if startup routine specified |                                                        |
